Base:
    model_root: './checkpoints/'
    num_workers: 3
    verbose: 1
    early_stop_patience: 2
    pickle_feature_encoder: True
    save_best_only: True
    eval_steps: null
    debug_mode: False
    group_id: null
    use_features: null
    feature_specs: null
    feature_config: null

DLRM_test:
    model: DLRM
    dataset_id: tiny_parquet
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.e-3
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 128
    embedding_dim: 4
    top_mlp_units: [64, 64, 64]
    bottom_mlp_units: [64, 64, 64]
    top_mlp_activations: ReLU
    bottom_mlp_activations: ReLU
    top_mlp_dropout: 0
    bottom_mlp_dropout: 0    
    interaction_op: dot
    batch_norm: False
    epochs: 1
    shuffle: True
    seed: 2022
    monitor: 'AUC'
    monitor_mode: 'max'

DLRM_default: # This is a config template
    model: DLRM
    dataset_id: TBD
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.e-3
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 4096
    embedding_dim: 40
    top_mlp_units: [64, 64, 64]
    bottom_mlp_units: [64, 64, 64]
    top_mlp_activations: ReLU
    bottom_mlp_activations: ReLU
    top_mlp_dropout: 0
    bottom_mlp_dropout: 0    
    interaction_op: dot
    batch_norm: False
    epochs: 100
    shuffle: True
    seed: 2022
    monitor: 'AUC'
    monitor_mode: 'max'

