### Tiny data for tests only
tiny_npz:
    data_root: ../../data/
    data_format: npz
    train_data: ../../data/tiny_npz/train.npz
    valid_data: ../../data/tiny_npz/valid.npz
    test_data: ../../data/tiny_npz/test.npz
