Base:
    model_root: './checkpoints/'
    num_workers: 3
    verbose: 1
    early_stop_patience: 2
    pickle_feature_encoder: True
    save_best_only: True
    eval_steps: null
    debug_mode: False
    group_id: null
    use_features: null
    feature_specs: null
    feature_config: null

DCNv3_test: # This is a config template
    batch_norm: False
    batch_size: 128
    dataset_id: tiny_npz
    dnn_activations: relu
    embedding_dim: 16
    embedding_regularizer: 0
    epochs: 1
    learning_rate: 1.0e-3
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    model: DCNv3
    monitor: 'AUC'
    monitor_mode: 'max'
    net_dropout: 0
    net_regularizer: 0
    num_cross_layers: 3
    num_heads: 1
    optimizer: adam
    seed: 2019
    shuffle: True
    task: binary_classification

DCNv3_default: # This is a config template
    batch_norm: False
    batch_size: 128
    dataset_id: tiny_npz
    dnn_activations: relu
    embedding_dim: 16
    embedding_regularizer: 0
    epochs: 1
    learning_rate: 1.0e-3
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    model: DCNv3
    monitor: 'AUC'
    monitor_mode: 'max'
    net_dropout: 0
    net_regularizer: 0
    num_cross_layers: 3
    num_heads: 1
    optimizer: adam
    seed: 2019
    shuffle: True
    task: binary_classification
