Base:
    model_root: './checkpoints/'
    num_workers: 3
    verbose: 1
    early_stop_patience: 2
    pickle_feature_encoder: True
    save_best_only: True
    eval_steps: null
    debug_mode: False
    group_id: null
    use_features: null
    feature_specs: null
    feature_config: null

MMoE_test:
    model: MMoE
    dataset_id: tiny_mtl
    loss: ['binary_crossentropy','binary_crossentropy']
    metrics: ['logloss', 'AUC']
    task: ['binary_classification','binary_classification']
    num_tasks: 2
    optimizer: adam
    learning_rate: 1.e-3
    num_experts: 8
    expert_hidden_units: [512,256,128]
    gate_hidden_units: [128, 64]
    tower_hidden_units: [128, 64]
    hidden_activations: relu
    net_regularizer: 0
    embedding_regularizer: 1.e-6
    batch_norm: False
    net_dropout: 0
    batch_size: 128
    embedding_dim: 128
    epochs: 50
    shuffle: True
    seed: 2023
    monitor: 'AUC'
    monitor_mode: 'max'