Base:
    model_root: './checkpoints/'
    num_workers: 3
    verbose: 1
    early_stop_patience: 2
    pickle_feature_encoder: True
    save_best_only: True
    eval_steps: null
    debug_mode: False
    group_id: null
    use_features: null
    feature_specs: null
    feature_config: null

AOANet_test:
    model: AOANet
    dataset_id: tiny_parquet
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.e-3
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 128
    embedding_dim: 4
    dnn_hidden_units: [64, 64, 64]
    dnn_hidden_activations: "ReLU"
    num_interaction_layers: 3
    num_subspaces: 4
    batch_norm: False
    net_dropout: 0
    epochs: 1
    shuffle: True
    seed: 2022
    monitor: 'AUC'
    monitor_mode: 'max'

AOANet_default: # This is a config template
    model: AOANet
    dataset_id: TBD # TBD is a place holder for assigning dataset_id
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.e-3
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 4096
    embedding_dim: 40
    dnn_hidden_units: [64, 64, 64]
    dnn_hidden_activations: "ReLU"
    num_interaction_layers: 3
    num_subspaces: 4
    batch_norm: False
    net_dropout: 0
    epochs: 100
    shuffle: True
    seed: 2022
    monitor: 'AUC'
    monitor_mode: 'max'

