### Tiny data for demo only
tiny_seq:
    data_root: ../data/
    data_format: parquet
    train_data: ../data/tiny_seq/train.parquet
    valid_data: ../data/tiny_seq/valid.parquet
    test_data: ../data/tiny_seq/test.parquet
