Base:
    model_root: './checkpoints/'
    num_workers: 8
    verbose: 1
    early_stop_patience: 2
    pickle_feature_encoder: True
    save_best_only: True
    eval_steps: null
    debug_mode: False
    group_id: null
    use_features: null
    feature_specs: null
    feature_config: null

QNN_alpha_default: # This is a config template
    model: QNN_alpha
    dataset_id: TBD
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.e-3
    embedding_regularizer: 1.e-5
    net_regularizer: 0
    batch_size: 10000
    embedding_dim: 16
    num_layers: 3
    num_row: 3
    net_dropout: 0.1
    num_heads: 1
    batch_norm: True
    epochs: 100
    shuffle: True
    seed: 2025
    monitor: {'AUC': 1, 'logloss': 0}
    monitor_mode: 'max'