name: jupyter-book

# Only run this when a tag is pushed
on:
  push:
    tags:
      - '*'
    branches:
    - main

# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    # Install dependencies
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
    - run: pip install jupyter-book==1.0.4.post1

    # Build the book
    - name: Build the book
      run: |
        jupyter-book build ./docs

    # Push the book's HTML to github-pages
    - name: Deploy github-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.JUPYTER_TOKEN }}
        external_repository: fuxictr/fuxictr.github.io
        publish_branch: main
        publish_dir: ./docs/_build/html
        exclude_assets: '_sources'
        destination_dir: ${{ startsWith(github.ref_name, 'v') && github.ref_name || 'latest' }}
